//
//  Constants.swift
//
//  Created by Sunil Datt Joshi on 08/04/17.
//  Copyright © 2018 Manoj Kumar Sahu. All rights reserved.
//

import Foundation
import UIKit

//Parameters Names
let cPassword           = "password"
let cNewPassword        = "newPassword"
let cConfirmPassword    = "confirm-password"
let cFullName           = "fullname"
let cPrivateMiles       = "private_mile"
let cUserName           = "username"
let cSplittCommentType  = "comment_status"
let cName               = "name"
let cEmail              = "email"
let cCountryCode        = "country_code"
let cMobile             = "mobile_number"
let cGender             = "gender"
let cDob                = "dob"
let cDeviceToken        = "deviceToken"
let cDeviceType         = "deviceType"
let cToken              = "token"
let cData               = "data"
let cPagination         = "pagination"
let cRewardData         = "rewardData"
let cCategoryId         = "category_id"
let cCategoryID         = "categoryID"
let cProCategory        = "splitt_pro_category"
let cSplittTitle        = "splitt_title"
let cBusinessname       = "businessname"
let cUserType           = "userType"
let cAnswer             = "answer"
let cSplittOption       = "splitt_option"
let cRedeem             = "redeem"
let ctransaction_id     = "transaction_id"
let cproduct_id         = "product_id"
let cStatus             = "status"


let cSplittRadius       = "splitt_radius"
let cFutureSplitt       = "future_splitt"
let cFutureDate         = "future_date"

let cCategoryName       = "category_name"
let cTimelineId         = "timeline_id"
let cTimelineName       = "timeline_value"
let cTimeline           = "timeline"

let cCity               = "city"
let cCount              = "count"

let cStronglyDisAgree   = "strongly_disagree"
let cDisagree           = "disagree"
let cNeutral            = "nuetral"
let cAgree              = "agree"
let cStronglyAgree      = "strongly_agree"
let cQuestion           = "survey_question"


let cFollowingId        = "following_id"
let cFollowingImage     = "following_image"
let cFollowingName      = "following_name"
let cFollowingRole      = "following_role"
let cFollowerId         = "follower_id"
let cFollowerImage      = "follower_image"
let cFollowerName       = "follower_name"
let cFollowerRole       = "follower_role"
let cFollowerData       = "follower_data"
let cFollowingData      = "following_data"
let cGroupData          = "group_data"
let cGroupId            = "group_id"
let cAction             = "action"
let cGroupinvite                         = "groupinvite"
let cDirect_split                        = "direct_split"
let cPublic_split                        = "public_split"
let cGroup_split                         = "group_split"


let cGroupImage         = "group_image"
let cGroupName          = "group_name"
let cGroupCreateImage   = "groupImage"
let cGroupCreatedBy     = "created_by"
let cId                 = "id"
let cSplittData         = "splitt_data"
let cRewardName         = "reward_name"
let cIsFollow           = "is_follow"
let cIsBlock            = "is_block"
let cUserId             = "user_id"
let cReceiverId         = "reciver_id"
let cBlockId            = "blocked_id"
let cUserImage          = "Userimage"
let cLoginType          = "loginType"
let cReward             = "reward"
let cRewardId           = "reward_id"
let cDay                = "day"
let cEndTime            = "end_time"
let cIsSelect           = "is_selected"
let cStartTime          = "start_time"
let cLatitude           = "latitude"
let cLocation           = "location"
let cLongitude          = "longitude"
let cBusinessLogoImage  = "Business_logo"
let cBusinessImage      = "business_image"
let cUserGps            = "user_gps"
let cDeleteType         = "delete_type"


let cSaveStatus         = "save_status"
let cQuestionDetail     = "question_detail"

let cQuestionId         = "questionID"
let cUserID             = "uid"
let cSplittVisibility   = "splitt_visibility"


let cQuestionNameYes    = "questionNameYes"
let cQuestionNameNo     = "questionNameNo"
let cTitleQuestion      = "title_question"
let cTitleName          = "q_title_name"
let cQuestionOne        = "survey_question_one"
let cQuestionTwo        = "survey_question_two"
let cQuestionThree      = "survey_question_three"
let cQuestionFour       = "survey_question_four"
let cQuestionFive       = "survey_question_five"
let cIsProAnonymous     = "pro_is_anonymous"
let cIsAnonymous        = "is_anonymous"
let cSplittVisibilityId = "visibility_id"
let cAddReward          =  "add_reward"
let cRewardType         = "reward_type"
let cRewardExpireTime   = "reward_expire_time"
let cRewardExpire       = "reward_expire"


let cBusinessVisibilityType = "business_visibility_type"
let cRewardCondition       = "reward_condition"
let cGroupIndividual    = "group_ind"


let cSplittMediaOne     = "splitt_media_one"
let cSplittMediaTwo     = "splitt_media_two"
let cSplittMediaThree   = "splitt_media_three"
let cSplittMediaFour    = "splitt_media_four"

let cSplittBanner       = "banner_media"
let cSplittThumbnail    = "thumbnail"

let cAnswerAn           = "answer_an"
let cAnswerBn           = "answer_bn"
let cAnswerCn           = "answer_cn"
let cAnswerDn           = "answer_dn"

let cAnswerAy           = "answer_ay"
let cAnswerBy           = "answer_by"
let cAnswerCy           = "answer_cy"
let cAnswerDy           = "answer_dy"

let cFax                = "fax"
let cTwitterLink        = "twitter_link"
let cFbLink             = "facebook_link"
let cInstaLink          = "instagram_link"
let cLinkedinLink       = "linkedin_link"
let cReferalType        = "referal_type"
let cBusinessName       = "business_name"
let cWebsiteInfo        = "website_info"
let cCategory           = "category"
let cReferelType        = "referel_type"
let cBioData            = "bio_data"
let cOperationDays      = "operation_day"
let cAddress            = "address"
let cBusinessImages     = "business_images"
let cImageId            = "image_id"
let cImages             = "image"
let cSocialId           = "social_id"
let cSocialType         = "social_type"
let cNotificationStatus = "notification_status"
let cFeedback           = "feedback"
let cBusinessCategory   = "business_category"
let cType               = "type"
let TotalRecord         = "totalRecords"
let MaxSize             = "maxPages"
let PageNumber          = "page_number"
let Pagination          = "pagination"

let FilterCurrent       = "filter_current"
let FilterExpires       = "filter_expired"
let FromDate            = "fromDate"
let ToDate              = "toDate"


let cContent            = "content"
let cNotification       = "notification"
let cBackGroundImage    = "backgroun_image"
let cSearch             = "search"
let cPageNumber         = "page_number"
let cPageSize           = "page_size"
let cOtherUserId        = "other_user_id"
let cFollowTo           = "follow_to"
let cSplittId           = "splitt_id"
let cComment            = "comment"
let cMemberId           = "member_id"
let cRating             = "rating"

let cSplittSendCount    = "splittSendCount"
let cSplittAnswersCount = "splittAnswersCount"
let cSplittRedeemCount  = "splittRedeemCount"
let cSplittViewCount    = "splittViewCount"
let cSplittSend         = "splittSend"
let cSplittAnswers      = "splittAnswers"
let cSplittRedeem       = "splittRedeem"
let cSplittView         = "splittView"


let cInternationalFilter = "international_filter"
let cOnlyConnection      = "onlyConnection"


let cFollowBy           = "follow_by"
let cRoleType           = "role_type"
let pNewConPassword     = "newPassword_confirmation"
let pEmail              = "email"
let pID                 = "id"
let pOTP                = "otp"
let pNotiTitle          = "notificationTitle"
let pName               = "userName"
let pUserImage          = "userImage"
let pLng                = "longitude"
let pIsAnonymous        = "is_anonymous"
let pVisibilityType     = "visibility_type"
let pAnswerC            = "answer_C"
let pVisibility         = "splitt_visibility"
let pAnswerType         = "answer_type"
let pAnswerB            = "answer_B"
let pLat                = "latitude"
let pAnswerA            = "answer_A"
let pPhotoAnswerType    = "photo_answer_type"
let pSplittTitle        = "splitt_title"
let pAnswerD            = "answer_D"
let pSplittType         = "splitt_type"
let pSplittDescription  = "splitt_description"
let pVisibilityId       = "visibility_id"
let cNotificationId     = "notification_id"


let cSplittCount        = "splitt_count"
let cFollowerCount      = "followers_count"
let cFollowingCount     = "followings_count"
let cGroupCount         = "groups_count"
let cUserRewardCount    = "user_reward_count"
let cFollowerStatus     = "follower_status"
let cBackGroundLogo     = "background_logo"
let cUserRewards        = "user_rewards"
let cLocationList       = "locationList"
let cLocationName       = "location_name"
let cLocationID         = "location_id"
let cCreatedAt          = "created_at"


//API Name
let GetAllCategory        = "getAllBusinessCategory"
let Logout                = "userlogout"
let MyProfile             = "myProfile"
let EditProfile           = "editProfile"
let FollowersList         = "followersList"
let FolloweringList       = "followingList"
let MyGroupList           = "myGroupList"
let RewardList            = "rewardList"
let BusinessProfile       = "myBusinessProfile"
let GetCategory           = "getAllCategory"
let GetTimeline           = "getAllTimeline"
let AddSplitt             = "addSplitt"
let GetProSplittCategory   = "getProSplittCategory"
let GetAllBusinessLocation = "getLocationList"
let GetPrivateMile         = "getPrivateMile"
let SaveProCategory        = "saveProCategory"
let AddProQuestions        = "addProQuestion"
let AddBusinessSplitt      = "addBusinessSplittCustom"
let AddBusinessProSplitt   = "addBusinessSplittPro"
let LikeSplitt             = "likeSplitt"
let ReportSplittApi        = "reportSplitt"
let SplittDetail           = "splittDetail"
let AllSplittFeeds         = "allSplittFeeds"
let TrendingSplittFeeds    = "trendingSplittFeeds"
let LocalSplittFeeds       = "localSplittFeeds"
let GroupSplittFeeds       = "groupSplittFeeds"
let DirectSplittFeeds      = "directSplittFeeds"
let CreateGroup            = "createGroup"
let NotificationList       = "notificationList"
let GetBothCategory        = "getBothCategory"
let cAnswerSplitt          = "answerCustomSplitt"
let CommentSplitt          = "commentSplitt"
let CommentListSplitt      = "commentSplittList"
let LikeListSplitt         = "likeSplittList"
let AddAnswer              = "answerSurveySplitt"
let cPaymentStatusApi      =  "payment"
let DeleteNotification     =  "notificationDelete"
let NotificationCount      =  "notificationCount"
let cEditBusinessSplittCustom = "editBusinessCustomSplitt"
let EditBusinessSplittTime  = "editBusinessSplittTime"
let EditBusinessSplittPro   = "editBusinessSplittPro"
let UpdateOptionTime        = "updateOptionTime"
let FollowUnfollow          = "followUnfollow"
let kCommentToggleApi       = "commentToggle"
let BlockUnblockUser        = "userblockunblock"
let CreateUser              = "userSignupLogin"
let UserReview              = "userReview"

// Get response Parameter name
let pResponseCode       = "responseCode"
let pResponseMessage    = "message"


struct INSTAGRAM_IDS {
    
    static let INSTAGRAM_AUTHURL = "https://api.instagram.com/oauth/authorize/"
    
    static let INSTAGRAM_APIURl  = "https://api.instagram.com/v1/users/"
    
    static let INSTAGRAM_CLIENT_ID  = "1c61ea7ab40e4fea9e99afb7a1b03630"
    
    static let INSTAGRAM_CLIENTSERCRET = "4c62b05173524c1fbc59eb2e8c040e2c"
    
    static let INSTAGRAM_REDIRECT_URI = "https://www.mobiloitte.com/"
    
    static let INSTAGRAM_ACCESS_TOKEN =  "access_token"
    
    static let INSTAGRAM_SCOPE = "basic"
    
}

